# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- dev

trigger: none

pool:
  vmImage: 'ubuntu-latest'

#steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
    - job: BuildFrontAndApi
      displayName: 'Build Front and API'
      steps:
      - script: |
          set -e
          echo MONGO_INITDB_ROOT_USERNAME=mongoadmin\nMONGO_INITDB_ROOT_PASSWORD=mongoadmin > database/secrets.env
          docker pull gearstocks/api_builder:latest
          docker-compose up front api_builder
          echo Front and Back successfully build.
        displayName: 'Front and API Compilation Check'
      - script: |
          set -e
          mkdir -p drop
          echo Archive Preparation

          rm database/secrets.env
          mv database drop/
          echo Database OK
          
          mkdir -p drop/api_builder/build
          mv api_builder/build/App drop/api_builder/build/
          mv api_builder/lib drop/api_builder/
          mv back drop/
          echo API OK

          mkdir -p drop/front
          mv front/dist drop/front/
          mv apache drop/
          echo Front OK

          echo Application KO
          echo Archive OK
        displayName: 'Archive preparation'
      - task: ArchiveFiles@2
        displayName: 'Archive Front and API files'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/drop'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true
      - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        artifact: drop
  - stage: Deploy
    displayName: Deploy
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: GearStockDev
        displayName: 'Deploy Dev'
        environment:
          name: 'Gearstocks Dev'
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
              - script: |
                  set -e
                  unzip $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip /home