version: 2
jobs:
  dev:
    docker:
      - image: ubuntu-latest
      - steps:
        - checkout
        - run: echo Test the pull request on dev.
        - run: echo MONGO_INITDB_ROOT_USERNAME=mongoadmin\nMONGO_INITDB_ROOT_PASSWORD=mongoadmin > database/secrets.env
        - run: docker-compose up front api_builder
        - run: echo Front and Back successfully build.

  master:
    docker:
      - image: ubuntu-latest
      - steps:
        - checkout
        - run: echo Test the pull request on master.
        - run: echo MONGO_INITDB_ROOT_USERNAME=mongoadmin\nMONGO_INITDB_ROOT_PASSWORD=mongoadmin > database/secrets.env
        - run: docker-compose up front api_builder
        - run: echo Front and Back successfully build.