version: 2
jobs:
  dev:
    docker:
      - image: ubuntu-latest
      - steps:
        - checkout
        - script: |
          echo Test the pull request on dev.
          set -e
          echo MONGO_INITDB_ROOT_USERNAME=mongoadmin\nMONGO_INITDB_ROOT_PASSWORD=mongoadmin > database/secrets.env
          docker-compose up front api_builder
          echo Front and Back successfully build.

  master:
    docker:
      - image: ubuntu-latest
      - steps:
        - checkout
        - script: |
          echo Test the pull request on master.
          set -e
          echo MONGO_INITDB_ROOT_USERNAME=mongoadmin\nMONGO_INITDB_ROOT_PASSWORD=mongoadmin > database/secrets.env
          docker-compose up front api_builder
          ##RUN UNIT TEST
          echo Front and Back successfully build.

workflows:
  version: 2
  build_and_test:
    jobs:
      - dev:
        filters:
          branches:
            only: dev
      - master:
        filters:
          branches:
            only: master